name: Tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  run:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [3.6, 3.7, 3.8]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        mamba-version: "*"
        channels: conda-forge

    - name: Conda install dependencies
      shell: bash -l {0}
      run: conda install python=${{ matrix.python-version }} pip cookiecutter ipywidgets yarn

    - name: Generate test project
      shell: bash -l {0}
      run: cookiecutter --config-file tests/testconfig.yml --no-input .

    - name: Run pip install
      shell: bash -l {0}
      run: python -m pip install ./jupyter-widget-testwidgets

    - name: Test install
      shell: bash -l {0}
      run: |
           test -d $CONDA_PREFIX/share/jupyter/nbextensions/@jupyter-widgets/jupyter-widget-testwidgets
           test -f $CONDA_PREFIX/etc/jupyter/nbconfig/notebook.d/jupyter_widget_example.json
           test -d $CONDA_PREFIX/share/jupyter/labextensions/@jupyter-widgets/jupyter-widget-testwidgets
           test -f $CONDA_PREFIX/share/jupyter/labextensions/@jupyter-widgets/jupyter-widget-testwidgets/package.json
